#!/usr/bin/env bash
# build-docs.sh: build the browsable DocFX documentation site locally.
#
# It generates API reference from the InductorParser XML doc comments,
# folds in the curated docs/ markdown and the readme (as the home page),
# and writes a static site to docs/docfx/_site.
#
# Usage:
#   ./build-docs.sh            # build once, output in docs/docfx/_site
#   ./build-docs.sh --serve    # build, then serve at http://localhost:8080
#
# A successful build leaves the site in docs/docfx/_site. The live site is deployed
# by the GitHub Actions workflow (.github/workflows/docs.yml) on push to master.
# Run this script for local preview. The workflow runs the same build.

set -euo pipefail

# Run from the repo root regardless of where the script is invoked.
repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$repo_root"

# WSL has no native `dotnet` but can call the Windows SDK via interop.
# Fall back to dotnet.exe when dotnet isn't on PATH. On Linux and Git Bash
# on Windows, `dotnet` is present and this stays "dotnet". Same pattern as
# test.sh.
dotnet_command=dotnet
if ! command -v dotnet >/dev/null 2>&1; then
    dotnet_command=dotnet.exe
fi

# Absolute GitHub blob base for rewriting links that point outside the docs
# set (into src/, E2ESamples/, ...) so they stay clickable on the published
# site. The repo can be private, so the site never hotlinks raw.githubusercontent
# content (that 404s for anonymous visitors); assets the site needs are bundled
# as DocFX resources instead (see the chart staging below).
blob_base="https://github.com/EricZinda/InductorCSParser/blob/master"

# The curated docs that belong on the public site. Everything else in docs/
# (BugSearchLog/, PotentialBugSources/, Archive/) is internal and stays out.
# The capitalized Primer3/Primer4 match the real filenames.
curated_docs=(
    primer1.md
    primer2.md
    primerFailure.md
    Primer3.md
    Primer4.md
    tutorial-peek.md
    InductorParserReference.md
    CodeArchitecture.md
    ErrorArchitecture.md
    TestArchitecture.md
    Terminology.md
    UnicodeGotchas.md
    UnicodeInternalsArchitecture.md
    MappingPositionsAfterNormalization.md
)

echo "=== Restoring DocFX (local tool) ==="
"$dotnet_command" tool restore

echo "=== Staging curated docs into docs/docfx/docs ==="
# Copy the curated docs flat into docs/docfx/docs so their mutual links (all flat,
# e.g. [ref](InductorParserReference.md)) keep resolving and DocFX rewrites
# them to .html. Rewrite parent-relative links (../E2ESamples, ../src, ...)
# to absolute GitHub blob URLs, since those targets aren't part of the site.
rm -rf docs/docfx/docs
mkdir -p docs/docfx/docs
for doc in "${curated_docs[@]}"; do
    sed "s#](\.\./#](${blob_base}/#g" "docs/${doc}" > "docs/docfx/docs/${doc}"
done

echo "=== Staging the benchmark chart into docs/docfx/images ==="
# The chart artifacts live under src/Benchmarks (regenerated by each benchmark
# run), outside the docs tree, so DocFX can't see them on its own. Copy them
# into docs/docfx/images, which docfx.json bundles as a site resource, so the home
# page can reference them with a relative path that works even when the repo is
# private. (docs/docfx/images is gitignored, like the other staged build outputs.)
rm -rf docs/docfx/images
mkdir -p docs/docfx/images
cp src/Benchmarks/performance-chart.jpg docs/docfx/images/
cp src/Benchmarks/performance-chart.html docs/docfx/images/

echo "=== Generating home page from readme.md ==="
# Use the readme as the site home so it stays the single source of truth.
# Prepend an H1 title (the readme opens with a paragraph, no heading of its
# own). Keep its docs/ links relative (they resolve to docs/docfx/docs above). Point
# the benchmark chart image and its interactive HTML at the bundled copies in
# images/ (staged above) so they work without the repo being public, and the
# other src/ links at GitHub blob URLs so they stay clickable.
{
    printf '# The Inductor Parser\n\n'
    sed \
        -e "s#](src/Benchmarks/performance-chart.jpg)#](images/performance-chart.jpg)#g" \
        -e "s#](src/Benchmarks/performance-chart.html)#](images/performance-chart.html)#g" \
        -e "s#](src/#](${blob_base}/src/#g" \
        readme.md
} > docs/docfx/index.md

echo "=== Cleaning previous output ==="
# DocFX doesn't delete stale files from a prior run, so wipe the generated API
# metadata and the rendered site before rebuilding. Without this, a doc or type
# removed from the inputs would linger in _site and get published.
rm -rf docs/docfx/api docs/docfx/_site

echo "=== Generating API metadata ==="
"$dotnet_command" docfx metadata docs/docfx/docfx.json

echo "=== Building the categorized API sidebar ==="
# The metadata step writes docs/docfx/api/toc.yml grouped by namespace, with every
# type entry indented two spaces ("  - uid:") and namespace entries at column 0.
# We replace it with a sidebar that groups every public type into task-based
# sections instead. There's no separate API index page: the top navigation's
# API entry (docs/docfx/toc.yml) lands on the Rules class with this sidebar
# next to it, and the sidebar is the categorized overview.
api_dir="docs/docfx/api"
all_type_uids=$(grep -E '^  - uid: ' "$api_dir/toc.yml" | sed -E 's/^  - uid: //')

# Editorial grouping for the API sidebar. Lines starting with "# " are section
# headings; every other non-blank line is a type uid placed under the current
# heading, in this order. This is the one hand-maintained list in the docs, so
# the completeness check below appends (and warns about) any public type that's
# missing rather than letting a newly added type silently drop off the sidebar.
api_sidebar_layout='# Building a Grammar
InductorParser.Rules
InductorParser.TokenSet
InductorParser.TokenSet.Ascii
InductorParser.LateBoundRule
InductorParser.SyntaxTree.FlattenType
# Starting a Parse
InductorParser.ParseOptions
InductorParser.ParseCancellation
InductorParser.Tracing.TraceLevel
# Parse Results
InductorParser.ParseResult
InductorParser.ParseOutcome
InductorParser.SyntaxTree.SourcePosition
InductorParser.SyntaxTree.SourceRange
InductorParser.SyntaxTree.Symbol
InductorParser.SyntaxTree.SymbolId
InductorParser.SyntaxTree.ParseContext
# Writing a Rule
InductorParser.Rule
InductorParser.Lexing.Lexer
InductorParser.Lexing.Token
InductorParser.Lexing.Lexer.Probe
InductorParser.Lexing.Lexer.Transaction
InductorParser.INormalizationReporter
InductorParser.Invariant
InductorParser.InductorParserBugException
# Unicode
InductorParser.Lexing.UnicodeEnvironment
InductorParser.Lexing.UnicodeImplementation
InductorParser.Lexing.GraphemeHelpers
InductorParser.Lexing.NormalizationHelpers
InductorParser.Lexing.RuneHelpers
# Infrastructure
InductorParser.SyntaxTree.SymbolRanges
InductorParser.InvariantInterpolatedStringHandler
InductorParser.Tracing.TraceInterpolatedStringHandler'

# Completeness check: warn (don't silently drop) if a public type is missing
# from the layout, or if the layout names a type that no longer exists.
layout_uids=$(printf '%s\n' "$api_sidebar_layout" | grep -Ev '^(#|$)')
missing=$(comm -23 <(printf '%s\n' "$all_type_uids" | sort -u) <(printf '%s\n' "$layout_uids" | sort -u))
stale=$(comm -13 <(printf '%s\n' "$all_type_uids" | sort -u) <(printf '%s\n' "$layout_uids" | sort -u))
if [ -n "$missing" ]; then
    echo "WARNING: public types missing from the API sidebar layout (appended under Uncategorized):" >&2
    printf '  %s\n' $missing >&2
fi
if [ -n "$stale" ]; then
    echo "WARNING: API sidebar layout names types that no longer exist:" >&2
    printf '  %s\n' $stale >&2
fi

# Sidebar grouped into the task-based sections above. Each "# Heading" becomes
# a collapsible group. Each uid becomes a type link under it.
{
    printf '### YamlMime:TableOfContent\n'
    printf 'items:\n'
    while IFS= read -r line; do
        case "$line" in
            '# '*) printf -- '- name: %s\n  items:\n' "${line#\# }" ;;
            '')    ;;
            *)     printf -- '  - uid: %s\n' "$line" ;;
        esac
    done <<< "$api_sidebar_layout"
    # Keep the sidebar complete: any type missing from the layout (already
    # warned about above) goes under its own group rather than vanishing.
    if [ -n "$missing" ]; then
        printf -- '- name: Uncategorized\n  items:\n'
        for uid in $missing; do printf -- '  - uid: %s\n' "$uid"; done
    fi
} > "$api_dir/toc.yml"

echo "=== Building the site ==="
# DocFX prints "Invalid file link" warnings for any broken cross-reference.
# Scan the output for those after a build to keep the site link-clean.
"$dotnet_command" docfx build docs/docfx/docfx.json

if [ "${1:-}" = "--serve" ]; then
    echo "=== Serving at http://localhost:8080 (Ctrl+C to stop) ==="
    "$dotnet_command" docfx serve docs/docfx/_site
fi
