<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <RootNamespace>InductorParser.Benchmarks</RootNamespace>
    <AssemblyName>Benchmarks</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" Version="0.14.0" />
    <PackageReference Include="Parlot" Version="1.4.0" />
    <PackageReference Include="Pidgin" Version="3.4.0" />
    <PackageReference Include="Sprache" Version="2.3.1" />
    <PackageReference Include="Superpower" Version="3.0.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="Pegasus" Version="4.1.0" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\InductorParser\InductorParser.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Json\PegasusParsers\JsonOptimized.peg" />
    <None Remove="Json\PegasusParsers\JsonWiki.peg" />
    <PegGrammar Include="Json\PegasusParsers\JsonOptimized.peg" />
    <PegGrammar Include="Json\PegasusParsers\JsonWiki.peg" />
  </ItemGroup>

</Project>
